apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.k8Name }}
  namespace: {{ .Values.k8Project }}
  annotations:
      app.kubernetes.io/part-of: ssm
spec:
  selector:
    matchLabels: 
      app: {{ .Values.k8Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: {{ .Values.k8Name }}
        phase: test
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
      - name: {{ .Values.k8Name }}
        image: '{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}'
        workingDir: /opt/ssm
        command: ["./ssm"]
        env:
        - name: CIPHER_OUTPUT_FORMAT
          value: {{ .Values.config.cipherOutputFormat }}
        - name: SSM_VERSION
          value: {{ .Chart.AppVersion }}
        ports:
          - containerPort: {{ .Values.service.port }}
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.port }}
            scheme: HTTP
