apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.k8ServiceName }}-{{ .Values.location }}"
spec:
  type: {{ .Values.service.type }}
  # loadBalancerSourceRanges:
  #   - {{ .Values.service.sourceRange }}
  ports:
    - name: rest
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.k8Name }}
